[package]
name = "exstemmers_native"
version = "0.1.0"
authors = []
edition = "2021"

[lib]
name = "exstemmers_native"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rust-stemmers = "1.2.0"
rustler = "0.32.1"
